# need macOS 10.15 for aligned_alloc
c_stdlib_version:  # [osx and x86_64]
  - 10.15          # [osx and x86_64]
# Build against Numpy 2.0.0rc1.
# Delete this file once Numpy 2.0.0 is out.
channel_sources:
  - conda-forge,conda-forge/label/numpy_dev
