travis:
  secure:
    BINSTAR_TOKEN: tifFNR4paJXELR3yRW2tEpw5nYYetBnlawBS6sLDw3RFLBELXgalb6EHfGl0yPDG+M1rFpXvkF6Y54st0AGjqS95wg9Jxy6LpkWNFYvsioE1CrP1h0K//74py0YMA6+y7k/kTh+jZkEBB4feFIikg1TL74REbpIRR7qTpcB4AudMEw5GaE8OtkPdjfPXue7FAGMTXLJDsGgDYKglLEY6gQmoyF3x1pfAW5EIlQ9k6pPcVch6QGuv5JYhfZjRsIK73LFEubgBpmBSu2DaygFHaX+rvxxdBBTtyUx4DJCyLtmyTuN0YWaKMEnaHTrAMJP0UWhDQp2cHnDlktGbU4KREsqd5qiazvtWJx1r3ON5YEs/W22eE1/ZHXh/s+fMBSSwx28/dqPENNujuGtUmafldAyJULptYT/Vae04FcBpWPP1lJ9yD5RvQE0fKOU81yd2vcGF1GXT3fSrj6J941YGMZ7NXyLM3dmQ66shtF/Kz+3XsDB+qivBDCiR1pEw9DwYgYrPsF4hSeNinlm99ORGWtCddviHY7j0839NermXRsEE7qaHXxNaSsCCwqaLHJnPKvcLK1b56HrjsAwJseCAM4gFf/jaxtdfeX6eWibdCNRhCmYYJz7Gqh8cmmodY3fEl9+IKGdo8l606DJaehz0/Ty2So395S/Oz4bADfBVN7I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
